# Generated by Django 3.2.9 on 2021-12-12 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosBem',
            fields=[
                ('id_estado_bem', models.AutoField(primary_key=True, serialize=False)),
                ('estado_bem', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NaturezasDespesa',
            fields=[
                ('id_natureza_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('cod_natureza_despesa', models.CharField(max_length=8)),
                ('desc_natureza_despesa', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SituacoesUsoBem',
            fields=[
                ('id_situacao_uso_bem', models.AutoField(primary_key=True, serialize=False)),
                ('situacao_uso_bem', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NotasFiscais',
            fields=[
                ('id_nota_fiscal', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sume.fornecedores')),
                ('id_natureza_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sume.naturezasdespesa')),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notasfiscais_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notasfiscais_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=80)),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marcas_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItensOrcamento',
            fields=[
                ('id_item_orcamento', models.AutoField(primary_key=True, serialize=False)),
                ('id_orcamento_id', models.IntegerField()),
                ('id_produto_id', models.IntegerField()),
                ('qtd', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itensorcamento_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itensorcamento_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItensNotaFiscal',
            fields=[
                ('id_item_nota_fiscal', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_servico', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sume.notasfiscais')),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itensnotafiscal_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itensnotafiscal_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bens',
            fields=[
                ('id_bem', models.AutoField(primary_key=True, serialize=False)),
                ('tombamento', models.CharField(max_length=10)),
                ('valor_aquisicao', models.DecimalField(decimal_places=7, max_digits=7)),
                ('data_lim_garantia', models.DateField()),
                ('data_fim_garantia', models.DateField()),
                ('data_inicio_uso', models.DateField()),
                ('observacoes', models.TextField()),
                ('dt_cad', models.DateField(auto_now_add=True)),
                ('dt_alt', models.DateField(auto_now=True, null=True)),
                ('id_estado_bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sume.estadosbem')),
                ('id_item_nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sume.itensnotafiscal')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sume.marcas')),
                ('id_situacao_uso_bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sume.situacoesusobem')),
                ('id_user_alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bens_user_alt', to=settings.AUTH_USER_MODEL)),
                ('id_user_cad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bens_user_cad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
